<?php

namespace Container8gnvDHE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFoodService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Y3VwTXA.App\Entity\Food' shared service.
     *
     * @return \App\Entity\Food
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Y3VwTXA": it references class "App\\Entity\\Food" but no such service exists.');
    }
}
