<?php

namespace ContainerKyESQR8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8ZUGGxHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8ZUGGxH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8ZUGGxH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'subscriptionRepository' => ['privates', 'App\\Repository\\SubscriptionRepository', 'getSubscriptionRepositoryService', true],
        ], [
            'subscriptionRepository' => 'App\\Repository\\SubscriptionRepository',
        ]);
    }
}
