<?php

namespace ContainerKyESQR8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S1rfVYYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s1rfVYY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s1rfVYY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'subscription' => ['privates', '.errored..service_locator.s1rfVYY.App\\Entity\\Subscription', NULL, 'Cannot autowire service ".service_locator.s1rfVYY": it references class "App\\Entity\\Subscription" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'subscription' => 'App\\Entity\\Subscription',
        ]);
    }
}
