<?php

namespace ContainerKyESQR8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Wx.x6CL.App\Entity\Subscription' shared service.
     *
     * @return \App\Entity\Subscription
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Wx.x6CL": it references class "App\\Entity\\Subscription" but no such service exists.');
    }
}
