<?php

namespace ContainerXMxbybC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O764uMXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o764uMX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o764uMX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AuthController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.spC.Z_T', 'get_ServiceLocator_SpC_ZTService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.q2ji3lu', 'get_ServiceLocator_Q2ji3luService', true],
            'App\\Controller\\SubscriptionController::delete' => ['privates', '.service_locator.s1rfVYY', 'get_ServiceLocator_S1rfVYYService', true],
            'App\\Controller\\SubscriptionController::edit' => ['privates', '.service_locator.s1rfVYY', 'get_ServiceLocator_S1rfVYYService', true],
            'App\\Controller\\SubscriptionController::index' => ['privates', '.service_locator.8ZUGGxH', 'get_ServiceLocator_8ZUGGxHService', true],
            'App\\Controller\\SubscriptionController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\SubscriptionController::show' => ['privates', '.service_locator.Wx.x6CL', 'get_ServiceLocator_Wx_X6CLService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AuthController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.spC.Z_T', 'get_ServiceLocator_SpC_ZTService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.q2ji3lu', 'get_ServiceLocator_Q2ji3luService', true],
            'App\\Controller\\SubscriptionController:delete' => ['privates', '.service_locator.s1rfVYY', 'get_ServiceLocator_S1rfVYYService', true],
            'App\\Controller\\SubscriptionController:edit' => ['privates', '.service_locator.s1rfVYY', 'get_ServiceLocator_S1rfVYYService', true],
            'App\\Controller\\SubscriptionController:index' => ['privates', '.service_locator.8ZUGGxH', 'get_ServiceLocator_8ZUGGxHService', true],
            'App\\Controller\\SubscriptionController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\SubscriptionController:show' => ['privates', '.service_locator.Wx.x6CL', 'get_ServiceLocator_Wx_X6CLService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AuthController::login' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SubscriptionController::delete' => '?',
            'App\\Controller\\SubscriptionController::edit' => '?',
            'App\\Controller\\SubscriptionController::index' => '?',
            'App\\Controller\\SubscriptionController::new' => '?',
            'App\\Controller\\SubscriptionController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuthController:login' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SubscriptionController:delete' => '?',
            'App\\Controller\\SubscriptionController:edit' => '?',
            'App\\Controller\\SubscriptionController:index' => '?',
            'App\\Controller\\SubscriptionController:new' => '?',
            'App\\Controller\\SubscriptionController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
