<?php

namespace ContainerXMxbybC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wx_X6CLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Wx.x6CL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wx.x6CL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'subscription' => ['privates', '.errored..service_locator.Wx.x6CL.App\\Entity\\Subscription', NULL, 'Cannot autowire service ".service_locator.Wx.x6CL": it references class "App\\Entity\\Subscription" but no such service exists.'],
        ], [
            'subscription' => 'App\\Entity\\Subscription',
        ]);
    }
}
