<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHlbQSK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHlbQSK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXHlbQSK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXHlbQSK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXHlbQSK\App_KernelDevDebugContainer([
    'container.build_hash' => 'XHlbQSK',
    'container.build_id' => '93d8f3e8',
    'container.build_time' => 1711889941,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXHlbQSK');
