<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCYUBbxO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCYUBbxO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCYUBbxO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCYUBbxO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCYUBbxO\App_KernelDevDebugContainer([
    'container.build_hash' => 'CYUBbxO',
    'container.build_id' => '43ff9f26',
    'container.build_time' => 1712806069,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCYUBbxO');
