<?php

namespace ContainerCYUBbxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PSHEbcHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pSHEbcH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pSHEbcH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'recipe' => ['privates', '.errored..service_locator.pSHEbcH.App\\Entity\\Recipe', NULL, 'Cannot autowire service ".service_locator.pSHEbcH": it references class "App\\Entity\\Recipe" but no such service exists.'],
        ], [
            'recipe' => 'App\\Entity\\Recipe',
        ]);
    }
}
