<?php

namespace ContainerCYUBbxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y3VwTXAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y3VwTXA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y3VwTXA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'food' => ['privates', '.errored..service_locator.Y3VwTXA.App\\Entity\\Food', NULL, 'Cannot autowire service ".service_locator.Y3VwTXA": it references class "App\\Entity\\Food" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'food' => 'App\\Entity\\Food',
        ]);
    }
}
