<?php

namespace ContainerCYUBbxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WM6N1avService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WM6N1av' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WM6N1av'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FoodController::delete' => ['privates', '.service_locator.Y3VwTXA', 'get_ServiceLocator_Y3VwTXAService', true],
            'App\\Controller\\FoodController::edit' => ['privates', '.service_locator.Y3VwTXA', 'get_ServiceLocator_Y3VwTXAService', true],
            'App\\Controller\\FoodController::index' => ['privates', '.service_locator.K9TtDds', 'get_ServiceLocator_K9TtDdsService', true],
            'App\\Controller\\FoodController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\FoodController::show' => ['privates', '.service_locator.vKi5DOv', 'get_ServiceLocator_VKi5DOvService', true],
            'App\\Controller\\RecipeController::delete' => ['privates', '.service_locator.vX_1fxJ', 'get_ServiceLocator_VX1fxJService', true],
            'App\\Controller\\RecipeController::edit' => ['privates', '.service_locator.vX_1fxJ', 'get_ServiceLocator_VX1fxJService', true],
            'App\\Controller\\RecipeController::index' => ['privates', '.service_locator.lCPwzF2', 'get_ServiceLocator_LCPwzF2Service', true],
            'App\\Controller\\RecipeController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\RecipeController::show' => ['privates', '.service_locator.pSHEbcH', 'get_ServiceLocator_PSHEbcHService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\FoodController:delete' => ['privates', '.service_locator.Y3VwTXA', 'get_ServiceLocator_Y3VwTXAService', true],
            'App\\Controller\\FoodController:edit' => ['privates', '.service_locator.Y3VwTXA', 'get_ServiceLocator_Y3VwTXAService', true],
            'App\\Controller\\FoodController:index' => ['privates', '.service_locator.K9TtDds', 'get_ServiceLocator_K9TtDdsService', true],
            'App\\Controller\\FoodController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\FoodController:show' => ['privates', '.service_locator.vKi5DOv', 'get_ServiceLocator_VKi5DOvService', true],
            'App\\Controller\\RecipeController:delete' => ['privates', '.service_locator.vX_1fxJ', 'get_ServiceLocator_VX1fxJService', true],
            'App\\Controller\\RecipeController:edit' => ['privates', '.service_locator.vX_1fxJ', 'get_ServiceLocator_VX1fxJService', true],
            'App\\Controller\\RecipeController:index' => ['privates', '.service_locator.lCPwzF2', 'get_ServiceLocator_LCPwzF2Service', true],
            'App\\Controller\\RecipeController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\RecipeController:show' => ['privates', '.service_locator.pSHEbcH', 'get_ServiceLocator_PSHEbcHService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\FoodController::delete' => '?',
            'App\\Controller\\FoodController::edit' => '?',
            'App\\Controller\\FoodController::index' => '?',
            'App\\Controller\\FoodController::new' => '?',
            'App\\Controller\\FoodController::show' => '?',
            'App\\Controller\\RecipeController::delete' => '?',
            'App\\Controller\\RecipeController::edit' => '?',
            'App\\Controller\\RecipeController::index' => '?',
            'App\\Controller\\RecipeController::new' => '?',
            'App\\Controller\\RecipeController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FoodController:delete' => '?',
            'App\\Controller\\FoodController:edit' => '?',
            'App\\Controller\\FoodController:index' => '?',
            'App\\Controller\\FoodController:new' => '?',
            'App\\Controller\\FoodController:show' => '?',
            'App\\Controller\\RecipeController:delete' => '?',
            'App\\Controller\\RecipeController:edit' => '?',
            'App\\Controller\\RecipeController:index' => '?',
            'App\\Controller\\RecipeController:new' => '?',
            'App\\Controller\\RecipeController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
