<?php

namespace ContainerCYUBbxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K9TtDdsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K9TtDds' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K9TtDds'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'foodRepository' => ['privates', 'App\\Repository\\FoodRepository', 'getFoodRepositoryService', true],
        ], [
            'foodRepository' => 'App\\Repository\\FoodRepository',
        ]);
    }
}
